import { useEffect, useState } from 'react';
import { request, jsonRequest, downloadCv } from '../../services/workflowService';
const blankInterview={applicationId:'',date:'',time:'',minutes:30,type:'video',location:'',status:'programada'};
export default function SelectionWorkspace(){
 const [selected,setSelected]=useState('');const [jobFilter,setJobFilter]=useState('');
 const [data,setData]=useState(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const [revision,setRevision]=useState(0);const [search,setSearch]=useState('');
 const [interview,setInterview]=useState(blankInterview);const [evaluation,setEvaluation]=useState({applicationId:'',test:'Evaluación técnica',minutes:30,status:'en_revision',details:[{area:'Conocimientos técnicos',score:0,note:''},{area:'Habilidades blandas',score:0,note:''}]});
 useEffect(()=>{let active=true;Promise.all([request('/api/recruiter/applications'),request('/api/recruiter/selection/interviews'),request('/api/recruiter/selection/evaluations')]).then(([applications,interviews,evaluations])=>{if(active)setData({applications,interviews,evaluations});}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[revision]);
 async function action(fn){if(busy)return;setBusy(true);setError('');setNotice('');try{await fn();setNotice('Cambios guardados.');setRevision(v=>v+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const changeInterview=e=>setInterview(p=>({...p,[e.target.name]:e.target.value}));
 const applications=data?.applications||[];
 const selectedApplication=applications.find(a=>String(a.id)===selected);
 function choose(a){setSelected(String(a.id));setInterview({...blankInterview,applicationId:String(a.id)});setEvaluation(p=>({...p,applicationId:String(a.id)}));}
 const select=(value,onChange)=><select className="block w-full rounded border p-2" required value={value} onChange={onChange}><option value="">Selecciona una postulación</option>{applications.map(a=><option value={a.id} key={a.id}>{a.name} — {a.job} ({a.code})</option>)}</select>;
 const cls='block w-full rounded border p-2';
 return <main className="space-y-6 p-6"><h1 className="text-2xl font-bold">Proceso de selección</h1>{error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status">{notice}</p>}{!data&&!error&&<p>Cargando…</p>}
 <section className="rounded border bg-white p-4"><h2 className="mb-3 text-xl font-bold">Postulaciones y CV</h2><input className={cls} aria-label="Buscar postulantes" placeholder="Nombre, vacante, formación o experiencia" value={search} onChange={e=>setSearch(e.target.value)}/>
 <label className="block my-3">Filtrar por oferta<select className={cls} value={jobFilter} onChange={e=>setJobFilter(e.target.value)}><option value="">Todas las ofertas</option>{[...new Map(applications.map(a=>[String(a.jobId),a.job])).entries()].map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label>
 <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr><th>Postulante</th><th>Vacante</th><th>Estado</th><th>CV</th><th>Acciones</th></tr></thead><tbody>{applications.filter(a=>(!jobFilter||String(a.jobId)===jobFilter)).filter(a=>`${a.name} ${a.job} ${a.educationText} ${a.experienceText}`.toLowerCase().includes(search.toLowerCase())).map(a=><tr key={a.id} className="border-t"><td className="p-3">{a.name}<br/><small>{a.email}</small><details className="mt-2"><summary className="cursor-pointer text-sm">Historial de estados</summary><ol className="text-sm">{(a.steps||[]).map((s,i)=><li key={i}>{s.date} — {s.label}</li>)}</ol></details></td><td>{a.job}</td><td><select aria-label={`Estado de ${a.name}`} disabled={busy} value={a.status} onChange={e=>action(()=>jsonRequest(`/api/recruiter/applications/${a.id}/status`,'PUT',{status:e.target.value}))}>{['recibida','en_revision','entrevista','aprobada','rechazada'].map(s=><option key={s}>{s}</option>)}</select></td><td><button onClick={()=>downloadCv(a.id).catch(e=>setError(e.message))} className="text-brand-red">Descargar PDF</button></td><td><button className="text-brand-red underline" onClick={()=>choose(a)}>Gestionar postulación</button></td></tr>)}</tbody></table></div></section>
 {selectedApplication&&<p role="status" className="rounded border bg-blue-50 p-3">Postulación seleccionada: <strong>{selectedApplication.name}</strong> — {selectedApplication.job} ({selectedApplication.code}). Los formularios de entrevista y evaluación están preparados para esta postulación.</p>}
 <section className="rounded border bg-white p-4"><h2 className="mb-3 text-xl font-bold">{interview.id?'Reprogramar / actualizar entrevista':'Programar entrevista'}</h2>
 <form onSubmit={e=>{e.preventDefault();action(async()=>{await jsonRequest('/api/recruiter/selection/interviews'+(interview.id?'/'+interview.id:''),interview.id?'PUT':'POST',{...interview,applicationId:Number(interview.applicationId),minutes:Number(interview.minutes)});setInterview(blankInterview);});}}><fieldset disabled={busy} className="grid gap-4 md:grid-cols-2">
 <label>Postulación{select(interview.applicationId,e=>setInterview(p=>({...p,applicationId:e.target.value})))}</label>
 <label>Fecha<input className={cls} name="date" type="date" required value={interview.date} onChange={changeInterview}/></label><label>Hora<input className={cls} name="time" type="time" required value={interview.time} onChange={changeInterview}/></label>
 <label>Duración (minutos)<input className={cls} name="minutes" type="number" min={10} max={240} required value={interview.minutes} onChange={changeInterview}/></label>
 <label>Modalidad<select className={cls} name="type" value={interview.type} onChange={changeInterview}><option value="video">Videollamada</option><option value="presencial">Presencial</option></select></label>
 <label>Lugar o enlace<input className={cls} name="location" required maxLength={255} value={interview.location} onChange={changeInterview}/></label>
 <label>Estado<select className={cls} name="status" value={interview.status} onChange={changeInterview}>{['programada','realizada','cancelada'].map(s=><option key={s}>{s}</option>)}</select></label>
 <div><button className="rounded bg-brand-red p-3 text-white">Guardar entrevista</button>{interview.id&&<button type="button" className="ml-3" onClick={()=>setInterview(blankInterview)}>Cancelar edición</button>}</div>
 </fieldset></form><p className="my-3 text-sm text-slate-600">La agenda compartida no permite entrevistas programadas que se superpongan.</p>
 {data?.interviews.map(i=><div className="flex flex-wrap justify-between gap-3 border-t py-3" key={i.id}><span>{i.name} — {i.date} {i.time} — {i.status}</span><button className="text-brand-red" onClick={()=>setInterview({...i,time:i.time.slice(0,5)})}>Editar entrevista</button></div>)}</section>
 <section className="rounded border bg-white p-4"><h2 className="mb-3 text-xl font-bold">Registrar evaluación</h2><form onSubmit={e=>{e.preventDefault();action(()=>jsonRequest('/api/recruiter/selection/evaluations','POST',{...evaluation,applicationId:Number(evaluation.applicationId),minutes:Number(evaluation.minutes)}));}}><fieldset disabled={busy} className="space-y-3">
 <label className="block">Postulación{select(evaluation.applicationId,e=>setEvaluation(p=>({...p,applicationId:e.target.value})))}</label>
 <label className="block">Evaluación<input className={cls} required maxLength={100} value={evaluation.test} onChange={e=>setEvaluation(p=>({...p,test:e.target.value}))}/></label>
 <label className="block">Duración en minutos<input className={cls} type="number" min={0} max={1440} value={evaluation.minutes} onChange={e=>setEvaluation(p=>({...p,minutes:e.target.value}))}/></label>
 {evaluation.details.map((c,index)=><div key={index} className="grid gap-3 md:grid-cols-3"><label>Criterio<input className={cls} required maxLength={100} value={c.area} onChange={e=>setEvaluation(p=>({...p,details:p.details.map((x,i)=>i===index?{...x,area:e.target.value}:x)}))}/></label><label>Puntaje (0–100)<input className={cls} type="number" min={0} max={100} required value={c.score} onChange={e=>setEvaluation(p=>({...p,details:p.details.map((x,i)=>i===index?{...x,score:Number(e.target.value)}:x)}))}/></label><label>Observación<input className={cls} maxLength={255} value={c.note} onChange={e=>setEvaluation(p=>({...p,details:p.details.map((x,i)=>i===index?{...x,note:e.target.value}:x)}))}/></label></div>)}
 <label className="block">Resultado<select className={cls} value={evaluation.status} onChange={e=>setEvaluation(p=>({...p,status:e.target.value}))}>{['en_revision','aprobado','no_aprobado'].map(s=><option key={s}>{s}</option>)}</select></label><button className="rounded bg-brand-red p-3 text-white">Guardar evaluación</button></fieldset></form>
 {data?.evaluations.map(e=><article className="border-t py-3" key={e.id}><strong>{e.name} — {e.test}</strong><p>{e.score}/100 · {e.status} · {e.evaluator}</p>{e.details.map((d,i)=><p key={i} className="text-sm">{d.area}: {d.score} — {d.note}</p>)}</article>)}</section>
 </main>;
}
